from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional, Union


class CompanyModel(BaseModel):
    id: int = Field(default=None, alias='id')
    code: int = Field(default=None, alias='code')
    customer_id: int = Field(default=None, alias='customer_id')
    company: str = Field(default=None, alias='company')
    name: Optional[str] = Field(default=None, alias='name')
    website: Optional[str] = Field(default=None, alias='website')
    email: str = Field(default=None, alias='email')
    phone1: Optional[str] = Field(default=None, alias='phone1')
    phone2: Optional[str] = Field(default=None, alias='phone2')
    document: Optional[str] = Field(default=None, alias='phone2')
    address_zipcode: Optional[str] = Field(default=None, alias='address_zipcode')
    address_street: Optional[str] = Field(default=None, alias='address_street')
    address_number: Optional[str] = Field(default=None, alias='address_number')
    address_block: Optional[str] = Field(default=None, alias='address_block')
    address_city: Optional[str] = Field(default=None, alias='address_city')
    address_state: Optional[str] = Field(default=None, alias='address_state')
    address_country: Optional[str] = Field(default=None, alias='address_country')
    address_latitude: Optional[str] = Field(default=None, alias='address_latitude')
    address_longitude: Optional[str] = Field(default=None, alias='address_longitude')
    address_map: Optional[str] = Field(default=None, alias='address_map')
    address_note: Optional[str] = Field(default=None, alias='address_note')
    bank_code: Optional[str] = Field(default=None, alias='bank_code')
    bank_name: Optional[str] = Field(default=None, alias='bank_name')
    bank_branch: Optional[str] = Field(default=None, alias='bank_branch')
    bank_account: Optional[str] = Field(default=None, alias='bank_account')
    bank_account_type: Optional[str] = Field(default=None, alias='bank_account_type')
    bank_account_owner: Optional[str] = Field(default=None, alias='bank_account_owner')
    bank_account_owner_document: Optional[str] = Field(default=None, alias='bank_account_owner_document')
    bank_account_note: Optional[str] = Field(default=None, alias='bank_account_note')
    note: Optional[str] = Field(default=None, alias='note')
    custom_fields: Optional[Union[List[Dict[str, Any]], List[List[Any]]]] = Field(default=None, alias='custom_fields')
    picture: Optional[str] = Field(default=None, alias='picture')
    created_at: str = Field(default=None, alias='created_at')
    updated_at: str = Field(default=None, alias='updated_at')
    deleted_at: Optional[str] = Field(default=None, alias='deleted_at')
